### ISSUE TITLE
port undefined in open command

### ISSUE THREAD

**Issue by dlants** [jason0x43/vim-tss#5]
When opening a new file,

```
"main.ts" 74L, 2488C
TSS: Starting server
TSS: Opening main.ts
TSS: Log: 11:31:52 Returning random file port
TSS: Log: 11:31:52 port was /var/folders/bn/tl38_05s0jg02hptdbm36z500000gp/T/vim-tsserve.38e986654d1f8449f028be62796d2ecd7cbbd423.sock
TSS: Log: 11:31:52 Started tsserver
TSS: Log: 11:31:52 Listening on port /var/folders/bn/tl38_05s0jg02hptdbm36z500000gp/T/vim-tsserve.38e986654d1f8449f028be62796d2ecd7cbbd423.sock...
TSS: Log: VIM_TSS_PORT=/var/folders/bn/tl38_05s0jg02hptdbm36z500000gp/T/vim-tsserve.38e986654d1f8449f028be62796d2ecd7cbbd423.sock
TSS: Server started on port /var/folders/bn/tl38_05s0jg02hptdbm36z500000gp/T/vim-tsserve.38e986654d1f8449f028be62796d2ecd7cbbd423.sock
TSS: Opening file main.ts
TSS: Opening main.ts
TSS: Log: /Users/dlants/.vim/plugged/vim-tss/bin/lib/client.js:90             throw new Error('A port is required');             ^  Error: A port is required     at Object.connect (/Users/dlants/.vim/plugged/vim-tss/bin/lib/client.js:90:1
9)     at Object.<anonymous> (/Users/dlants/.vim/plugged/vim-tss/bin/open.js:9:10)     at Module._compile (module.js:570:32)     at Object.Module._extensions..js (module.js:579:10)     at Module.load (module.js:487:32)     at tryModuleLoa
d (module.js:446:12)     at Function.Module._load (module.js:438:3)     at Module.runMain (module.js:604:10)     at run (bootstrap_node.js:394:7)     at startup (bootstrap_node.js:149:9)
TSS: Open main.ts ended
TSS: Open main.ts ended
```

It seems like the tss server is starting up correctly, and setting $VIM_TSS_PORT. However, this environment variable is not making it into subsequent commands.

I tried looking through at how this env is meant to make it into subsequent invocations of Tss commands, but unfortunately here I was unable to follow the vimscript.

**Comment by dlants** [comment]
Ah figured it out!

Turns out, vim runs openFile several times before the server is initialized. Consequently, the first several responses don't have the environment variable set, and I was seeing responses to those earlier requests in the error log.
